# See https://pre-commit.com
repos:
  - repo: local
    hooks:
      - id: commit-msg
        name: conventional commit message
        entry: bash scripts/check-commit-msg.sh
        language: system
        pass_filenames: true
